spring.application.name=gateway-service
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=patient-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/patients/**